version: '3.8'
volumes:
  postgres_db_dev: {}
services:
  db:
    image: postgres
    env_file:
      - test.env
    ports:
      - "5433:5432"
    volumes:
      - postgres_db_dev:/var/lib/postgresql/data
    networks:
      - mynetwork

  django:
    image: lkh6035/picknpop-be-user:v0.1.8
    env_file:
      - test.env
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - mynetwork
    restart: always
    command:
      - bash
      - -c
      - |
        ./wait-for-it.sh db:5432 -t 20 -- echo "picknpop is up"
        python manage.py migrate
        python manage.py runserver 0.0.0.0:8000
  fastapi:
    image: lkh6035/picknpop-be:v0.1.5
    env_file:
      - test.env
    ports:
      - "18000:18000"
    depends_on:
      - db
      - django
    networks:
      - mynetwork
    restart: always
    command:
      - bash
      - -c
      - |
        ./wait-for-it.sh db:5432 -t 20 -- echo "picknpop is up"
        uvicorn app.main:apps --host 0.0.0.0 --port 18000
  next-js:
    image: lkh6035/picknpop-fe:v0.1.7-local
    ports:
      - "3000:3000"
    depends_on:
      - db
      - django
      - fastapi
    networks:
      - mynetwork
    restart: always
    command: ["yarn", "start", "-H", "0.0.0.0"]
networks:
  mynetwork:
